# Generated by Django 4.1.1 on 2022-10-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Imagem',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='Legenda',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titulo',
        ),
    ]
