# Generated by Django 4.1.1 on 2022-10-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_author_post_autor_rename_content_post_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Imagem',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Texto',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Legenda',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titulo',
            new_name='title',
        ),
    ]
